POST http://localhost:8000/api/class/add
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjU4NDI4ZTA4OThkNzBhZjMxYWFlMSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczNDcyMTQ5OCwiZXhwIjoxNzM0NzI4Njk4fQ.GxKnGr3nquJ6qx7kp_E6Rp6xHBBi8KD5oQ-m5j3NLFg

{
  "name": "form 1",
  "teacherId": "676bf4b6734834603c949556"
 
}
###
GET http://localhost:8000/api/classes
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGM0N2M4Y2FlZTI1Mzc0N2UwNmExNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczMjI4MjA2MywiZXhwIjoxNzMyMjg5MjYzfQ.PypO9T8ifSmkKo4zazK5mvSYW2EzI1Xhotd0APr2nj0


###
DELETE http://localhost:8000/api/class/6765d39af001502d895e2322
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGM0N2M4Y2FlZTI1Mzc0N2UwNmExNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczMjE4Mjg3OCwiZXhwIjoxNzMyMTkwMDc4fQ.1oJy1Ljuen7mwQO0yffaJNL9WSAzfr599uywg9Z1Hss

###
PUT http://localhost:8000/api/class/677e4acb971e4d5ecca01eff
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NjU4NDI4ZTA4OThkNzBhZjMxYWFlMSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTczNDcyMTQ5OCwiZXhwIjoxNzM0NzI4Njk4fQ.GxKnGr3nquJ6qx7kp_E6Rp6xHBBi8KD5oQ-m5j3NLFg

{
  "name": "form 2",
  "teacherId": "676bf4b6734834603c949556"
 
}


###
POST http://localhost:8000/api/slack/events
Content-Type: application/json

{
  "token": "nZO1yBysCJIIjqXBoD7uW356",
  "team_id": "T01HM9SDWQ4",
  "context_team_id": "T01HM9SDWQ4",
  "api_app_id": "A088F1BKGTX",
  "event": {
    "user": "U07T62G2JSD",
    "type": "message",
    "ts": "1736841059.367589",
    "client_msg_id": "0dca8c6e-8e28-42ce-9b9c-1f54688c6cf0",
    "text": "another test",
    "team": "T01HM9SDWQ4",
    "blocks": [],
    "channel": "D0896NUE9JL",
    "event_ts": "1736841059.367589",
    "channel_type": "im"
  },
  "type": "event_callback",
  "event_id": "Ev088FDJST3P",
  "event_time": 1736841059,
  "authorizations": [
    {
      "enterprise_id": null,
      "team_id": "T01HM9SDWQ4",
      "user_id": "U088B9YNZP0",
      "is_bot": true,
      "is_enterprise_install": false
    }
  ],
  "is_ext_shared_channel": false,
  "event_context": "4-eyJldCI6Im1lc3NhZ2UiLCJ0aWQiOiJUMDFITTlTRFdRNCIsImFpZCI6IkEwODhGMUJLR1RYIiwiY2lkIjoiRDA4OTZOVUU5SkwifQ"
}
