POST http://localhost:8000/api/event/add
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmRiMzRhNjk3MjQyZGViNzMwOGRhOSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJwZW5pbmFoIG11cmluZ2kiLCJpYXQiOjE3Mzg3NjQwODYsImV4cCI6MTczODc3MTI4Nn0.9YU8rcv-7ywzHssVnIMP2yLKXMW94CV5_lIlDc_v46w

{
  "title": "team lunch",
  "start": "2025-03-06T14:00:00Z",
  "end": "2025-03-06T16:00:00Z"
}
###
GET http://localhost:8000/api/events
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODc2M2I1OGFkZjlkYWQ0MjFiMGIyNyIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJzaW1vbiBrYW1hdSIsImlhdCI6MTc0MDU2MjYwNCwiZXhwIjoxNzQwNTY5ODA0fQ.HIZsWTjq7T4Y1d-xPcaSRa33U2cEGDincU_AQfJKp54



###
DELETE http://localhost:8000/api/event/67befa5d1058690f95ed214e
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ODc2M2I1OGFkZjlkYWQ0MjFiMGIyNyIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJzaW1vbiBrYW1hdSIsImlhdCI6MTc0MDU2MjYwNCwiZXhwIjoxNzQwNTY5ODA0fQ.HIZsWTjq7T4Y1d-xPcaSRa33U2cEGDincU_AQfJKp54

###
PUT http://localhost:8000/api/event/67a22893046a839845a66722
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmRiMzRhNjk3MjQyZGViNzMwOGRhOSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJwZW5pbmFoIG11cmluZ2kiLCJpYXQiOjE3Mzg2OTg3NjgsImV4cCI6MTczODcwNTk2OH0.wSC7n1xi9AgLGjltePPqlWW6F1TTHsErFtDoU299v4U

{
  "title": "cut one",
   "start": "2025-02-05T08:30:00.000Z",
    "end": "2025-02-05T09:29:00.000Z"

}