### HEALTH CHECK
GET http://localhost:8000/
###
GET http://localhost:8000/api/users
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzE5Njc3Zjc4OTYyMDNjNzM1M2Q5MCIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJzaW1vbiBrYW1hdSIsImlhdCI6MTc0MDc0NDIyMywiZXhwIjoxNzQwNzUxNDIzfQ.-Neb8jEQ9u3llBJTjTUM0_Y141TYv3uImnk_ejfD-mk

### registering a user 
POST http://localhost:8000/api/users/add
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzE5Njc3Zjc4OTYyMDNjNzM1M2Q5MCIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJzaW1vbiBrYW1hdSIsImlhdCI6MTc0MDc0NDIyMywiZXhwIjoxNzQwNzUxNDIzfQ.-Neb8jEQ9u3llBJTjTUM0_Y141TYv3uImnk_ejfD-mk

{
  "name": "simon kamau",
  "email": "simogatuma12@gmail.com",
  "role": "admin",
  "phone": "+254759717749",
  "address": "Thika",
  "gender": "Male"
}

### login
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "email": "simogatuma12@gmail.com",
  "password": "7h1exkti"
}
###
POST http://localhost:8000/api/user/password/67c19677f7896203c7353d90
Content-Type: application/json

{
  "oldPassword": "7h1exkti",
  "newPassword": "7h1exkti"
}

### delete a user
DELETE http://localhost:8000/api/users/67c19677f7896203c7353d90
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzE5Njc3Zjc4OTYyMDNjNzM1M2Q5MCIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJzaW1vbiBrYW1hdSIsImlhdCI6MTc0MDc0NDIyMywiZXhwIjoxNzQwNzUxNDIzfQ.-Neb8jEQ9u3llBJTjTUM0_Y141TYv3uImnk_ejfD-mk

###
GET http://localhost:8000/api/users/66dc47c8caee253747e06a15
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZGM0N2M4Y2FlZTI1Mzc0N2UwNmExNSIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTcyNTcxNDA0OCwiZXhwIjoxNzI1NzIxMjQ4fQ.Ls8o-D3kX-Gr1RDw2BiNmcpFjF8-hv5V2zdL01DYLaY


### registering a user 
PUT  http://localhost:8000/api/user/678763b58adf9dad421b0b27
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NmRiMzRhNjk3MjQyZGViNzMwOGRhOSIsInJvbGUiOiJhZG1pbiIsIm5hbWUiOiJwZW5pbmFoIG11cmluZ2kiLCJpYXQiOjE3NDAzODg3ODgsImV4cCI6MTc0MDM5NTk4OH0.6ULE-v03uy6lhGOn0LaTpFC6DNuB3kOUDoiw-KK2QbY

{
   "name": "simon kamau",
    "password": "kamau"
 
}

###
POST http://localhost:8000/api/create/conversation
Content-Type: application/json


{
  "contactId": "+254759717759",
  "inboxId": "byVSmzKXrDn5aEV77qpxhuqz", 
  "messageContent": "Hello! How can I assist you today?"
}

